import sqlite3
conn = sqlite3.connect("G:/$XBVR/xbvr/main.db")
c = conn.cursor()
c.execute("SELECT tattoos, piercings, aliases, image_arr FROM actors WHERE id=3729")
r = c.fetchone()
print("tattoos:", repr(r[0]))
print("piercings:", repr(r[1]))
print("aliases:", repr(r[2]))
print("image_arr:", repr(r[3][:200] if r[3] else None))
conn.close()
